### ISSUE TITLE
Besides contrastive_train.sh, the other scripts in bash_scripts are not required?

### ISSUE THREAD

**Issue by gangxu822** [SarahRastegar/SelEx#3]
Besides contrastive_train.sh, the other scripts in bash_scripts are not required?

**Comment by SarahRastegar** [comment]
If you use "python contrastive_training.py" the extract features and Kmeans will be run automatically. Since I relied on the Python script, make sure the hyperparameters are similar, but if they are, yes it runs the other parts automatically.
