### ISSUE TITLE
The error is as follows, how to solve the problem?

### ISSUE THREAD

**Issue by gangxu822** [SarahRastegar/SelEx#5]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/nas/n/code/SelEx/methods/contrastive_training/contrastive_training.py", line 719, in <module>
    state_dict = torch.load(pretrain_path, map_location='cpu')['teacher']
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'teacher'

**Comment by SarahRastegar** [comment]
There were some differences between different versions of VIT in how they separate 'teacher' and 'student'. Make sure to load the teacher weights in the VIT (with whatever version you use) to reproduce the results.

**Comment by gangxu822** [comment]
Can you give me a download address, suitable for your code pth model version

**Comment by SarahRastegar** [comment]
Sure this is the pth model we used for dinov1 experiments:
https://drive.google.com/file/d/1LmGbwaE8afmRTUp4G7Xlb7_0xRWfudgF/view?usp=drive_link
